version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing source dependencies...
      - npm --prefix walking-library install 
  build:
    commands:
      - echo Build started on `date`
      - npm --prefix walking-library run build 
artifacts:
  files:
    - '**/*'
  base-directory: walking-library/dist
